#!/usr/bin/env python3
"""Build data/mocktests.js from the Ditectrev DVA-C02 README.

Source repo (clone under /tmp): github.com/Ditectrev/
  Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers

Parses every `### question` block, its `- [ ]` / `- [x]` options and any
images, then emits `window.DVA_MOCKTESTS`. Copies referenced images into
mock-images/. Questions here are independent of the existing question_bank.
"""
import json, os, re, shutil, sys

REPO = "/tmp/ditectrev-dva"
README = os.path.join(REPO, "README.md")
PROJ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # project root
OUT_JS = os.path.join(PROJ, "data", "mocktests.js")
IMG_SRC = os.path.join(REPO, "images")
IMG_DST = os.path.join(PROJ, "mock-images")

PER_TEST = 65
DURATION_MIN = 130
PASS_SCORE = 720

LETTERS = "ABCDEFGHIJ"


def img_path(line):
    m = re.search(r'!\[[^\]]*\]\(([^)\s]+)', line)
    return m.group(1) if m else None


def parse():
    if not os.path.exists(README):
        sys.exit("ERROR: %s not found. Clone the Ditectrev DVA repo to %s first." % (README, REPO))
    lines = open(README, encoding="utf-8").read().split("\n")
    questions, i, n = [], 0, len(lines)
    while i < n:
        line = lines[i]
        if line.startswith("### "):
            q = {"question": line[4:].strip(), "images": [], "options": []}
            questions.append(q)
            i += 1
            while i < n and not lines[i].startswith("### ") and "⬆ Back to Top" not in lines[i]:
                l = lines[i]
                mo = re.match(r'^\s*-\s*\[( |x)\]\s*(.*)$', l)
                if mo:
                    q["options"].append({"text": mo.group(2).strip(),
                                          "correct": mo.group(1) == "x", "image": None})
                else:
                    im = img_path(l)
                    if im:
                        if q["options"] and q["options"][-1]["image"] is None:
                            q["options"][-1]["image"] = im
                        else:
                            q["images"].append(im)
                i += 1
            continue
        i += 1
    return [q for q in questions if len(q["options"]) >= 2]


def rewrite_img(p):
    # images/questionXX.jpg -> mock-images/questionXX.jpg
    return "mock-images/" + os.path.basename(p)


def main():
    raw = parse()
    needed = set()
    questions = []
    for idx, q in enumerate(raw, start=1):
        opts = []
        correct = []
        for oi, o in enumerate(q["options"]):
            letter = LETTERS[oi]
            img = None
            if o["image"]:
                needed.add(o["image"])
                img = rewrite_img(o["image"])
            opts.append({"letter": letter, "text": o["text"], "image": img})
            if o["correct"]:
                correct.append(letter)
        qimgs = []
        for im in q["images"]:
            needed.add(im)
            qimgs.append(rewrite_img(im))
        questions.append({
            "id": idx,
            "question": q["question"],
            "images": qimgs,
            "options": opts,
            "correct": correct,
            "multi": len(correct) > 1,
        })

    # static tests: consecutive slices of PER_TEST
    static = []
    start = 0
    t = 1
    while start < len(questions):
        count = min(PER_TEST, len(questions) - start)
        static.append({"id": "mock-%d" % t, "title": "Mock Test %d" % t,
                       "start": start, "count": count})
        start += count
        t += 1

    data = {
        "exam": "AWS Certified Developer - Associate (DVA-C02)",
        "source": "Ditectrev DVA-C02 Practice Tests (github.com/Ditectrev)",
        "durationMinutes": DURATION_MIN,
        "passingScore": PASS_SCORE,
        "scaleMin": 100,
        "scaleMax": 1000,
        "questionsPerTest": PER_TEST,
        "questions": questions,
        "staticTests": static,
    }

    os.makedirs(os.path.dirname(OUT_JS), exist_ok=True)
    with open(OUT_JS, "w", encoding="utf-8") as f:
        f.write("/* GENERATED by tools/build_mocktests.py — do not edit by hand. */\n")
        f.write("window.DVA_MOCKTESTS = ")
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write(";\n")

    # copy images
    os.makedirs(IMG_DST, exist_ok=True)
    copied = 0
    for im in sorted(needed):
        src = os.path.join(REPO, im)
        dst = os.path.join(IMG_DST, os.path.basename(im))
        if os.path.exists(src):
            shutil.copyfile(src, dst)
            copied += 1
        else:
            print("  WARN missing image:", src)

    single = sum(1 for q in questions if not q["multi"])
    multi = sum(1 for q in questions if q["multi"])
    print("questions:      ", len(questions))
    print("  single-answer:", single)
    print("  multi-answer: ", multi)
    print("static tests:   ", len(static), "->", [s["count"] for s in static])
    print("images needed:  ", len(needed), "| copied:", copied)
    print("wrote:          ", OUT_JS)


if __name__ == "__main__":
    main()
